### PR TITLE
a proposal for guest articles?

### PR DESCRIPTION
**Pull request by spicata**
have a look at the differences

### CODE REVIEW

**Comment by EddieTheEd** [comment]
No. 

I think hub note works well, and your idea is ineffective.

**Comment by EddieTheEd** [comment]
gfbsf
e5yhrn



wedES EDQRd edward sus and s\dumb f upid sidefio\\\eie\\ ediot

**Comment by EddieTheEd** [comment]
;
sadvefbg

**Comment by EddieTheEd** [comment]
woops/wd.

**Comment by spicata** [comment]
excuse me?

**Comment by EddieTheEd** [comment]
Sorry my beloved pranav got onto my gmails

**Pull request closed without merging**
